### ISSUE TITLE
API is not functional

### ISSUE THREAD

**Issue by kdesroches89** [Cebeerre/VerisureEUAPI#2]
Hello,

Since the new "new verisure" application, the old one no longer works. Is there a solution? 

Thanks

**Comment by Cebeerre** [comment]
Yes, they added a new parameter called ```callby```, that is just an identification of the device and version. Just try to add to the commands payload something like that:

```
callby=AND_61
```

I modified the API doc like 3 months ago including this.

**Comment by kdesroches89** [comment]
The parameter is already present : callby=AND_61 : 

![Capture d’écran du 2021-03-17 21-25-39](https://user-images.githubusercontent.com/75026748/111533840-881e4b00-8767-11eb-953d-d659dc71fa25.png)

Message : "The MyVerisure app has been replaced by My New Verisure. Please download the new app"
https://play.google.com/store/apps/details?id=com.verisure.securitasdirect.owa&hl=fr&gl=US

![Screenshot_2021-03-17 https alarme kikimath net](https://user-images.githubusercontent.com/75026748/111533358-fa426000-8766-11eb-9350-a324b1f98d40.png)

**Comment by Cebeerre** [comment]
Change the ID in your code to be Android based as well:

So, from this:

```
		'ID' =>  "IPH_________________________".$_SESSION["token"],
```

To this:

```
		'ID' =>  "AND_________________________".$_SESSION["token"],
```

**Comment by kdesroches89** [comment]
Hi,

I replaced it well but it does not change anything, there is still the message indicating to switch to the new verisure application

**Comment by Cebeerre** [comment]
Could you try this and see if it works for you ?

https://github.com/Cebeerre/pysecuritas

**Comment by kdesroches89** [comment]
It works fine. So I took the opportunity to update the calls and the API code in PHP: https://github.com/kdesroches89/verisure-api-php. Thank you for the help .
