### ISSUE TITLE
Other API parameters

### ISSUE THREAD

**Issue by kdesroches89** [Cebeerre/VerisureEUAPI#3]
Hi @Cebeerre while searching a bit i found other API parameters on https://community.home-assistant.io/t/securitas-direct-verisure-eu-custom-component-testers-wanted/70239/15. Would it be possible to get the GET and POST parameters from what had been posted in order to complete ? 

List of https://community.home-assistant.io/t/securitas-direct-verisure-eu-custom-component-testers-wanted/70239/15 : 

LOGIN
CLS
INS
SRV
ARM
ARMDAY
ARMNIGHT
ARMANNEX
DARMANNEX
PERI
DARM
IMG
EST
CAMLOG
CAMS
VIDS
VID
UPDCAM
CAMPSRS
INSTWORDS
INSTWORDSUPD
INSTWORDSUPD2
BILLS
IDENT
SECONDUSERS
PLAN
CONTACT
PLANUPD
CONTACTUPD
CONTACTADD
CONTACTDEL
SCHCDDEL
KEY
KEYUPD
ACT_V2
PANELCONF
PANELCONFUPD
MYINSTALLATION
DEVUPD
ATC
SECRETWORD
SRVDOMO
DOMO
DOOR
INF
CALLRING
SCHCDLIST
SCHCDADD
SCHCDUPD
SCHCDDISABLE
REMEMBERUSER
MYSD
MYSDCREATE
ALLINONE
SRVCOMMDATA
SRVCOMMDATAUPD
SRVCOMMDATAUPD2
SECONDUSERADD
SECONDUSERADD2
SECONDUSERDEL
SCHCDPROTECT
CONFIG
SOMFYSTATUS
CAMPAING
CRIALUPD
UPDPUSHSTATUS
SECONDINSTALLADD
SECONDINSTALLADD2
THUMBNAIL
UPDPROMPT
DIYRECEIVED
DIYRESEND
DIYCALLME
DIYINIT
DIYGETTAMPERS
DIYCHECK
DIYCONTINGENCIA
DIYEXTENDTIME
GETCAPMANT
SCHMANT
SENDOTPS
SENDOTP
SECUREACTIONS
SECUREACTION
GCMANT
GCCAPACITY
GCCANCELMANT
GCSCHMANT
CTCMFM
CONFORT
TEMP
HUM
AIRQ
GETCONFIGDDI
SETCONFIGDDI
SCHLIST
SCHADD
SCHUPD
SCHDEL
SCHLEGAL
SCHNOT
SCHUPDONFLY
GETASI
ASILEGAL
BAJAASI
ALTAASI
ASIRES
ASISOS
ACOMPGETTIMERS
ACOMPTRACKING
ACOMPCANCEL
GETTRACKERDATA
UPDORTRACK
GETONROADKEYDATA
UPDORKEY
NSR
GDPRPOPUP
GDPR
UPDGDPR
FIRSTCHGPASS
RESETPASS
RESETPASS2
SENDINST
ALTAWEB
ALTAWEB2
LOCKSMITH
ACCEPTLEGALSLOCKSMITH
ASKLOCKSMITH
CANCELLOCKSMITH
GETALLLOCKSMITHS
GETSECURITYINFO
CHECKOTP
PENDINGBILLSLIST

**Comment by Cebeerre** [comment]
Hi @kdesroches89 , I actually posted that list on the home assistant forum :) 

Honestly speaking I don't have time enough to debug all of these ... and some of them require from securitas devices that I don't actually have under my contract (like the sentinel device). Some others that I actually tried, allow you to change your PASSCODE, add users, and stuff like that ... something that I though it wasn't actually useful to add to a smart home hub. 

Happy to accept pull requests though ;)
